name: Build and Deploy
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build
        run: |
          # make file executable
          chmod +x "${GITHUB_WORKSPACE}/scripts/build.sh"

          sh "${GITHUB_WORKSPACE}/scripts/build.sh"

      - name: Archive Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dev-build
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dev-build
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: pomo-hero-test
