name: E2E on Chrome
on:
  schedule:
    - cron: "0 10 * * *"
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: source/v1/cypress_tests/cypress/integration/tests/*.js